### ISSUE TITLE
Video Player doesn't work

### ISSUE THREAD

**Issue by ram2141** [islem19/TV-Live-Stream#1]
Hello @islem19 ,

Thanks for developing and sharing your work. I have forked your app and modified data.json file with live tv m3u, mp4 and m3u8 links but none of those links work in app. It turns to black screen nothing plays. I tested those link in vlc and mx player, it works fine. Is there any way to fix it? Thanks.

**Comment by islem19** [comment]
Hey @ram2141 
i have tested the video player and it works fine on both MP4 and M3U8 links, make sure you correctly parse the data.json file and get the link from json correctly, try to put the link directly in the player and see if it works there first.

**Comment by ram2141** [comment]
Hey @islem19 ,

Thanks for replying me back. I have put m3u8 link and mp4 in jason file. I am new to android and don't know how to parse from data.json file or put the link directly in player. I tested those link in vlc and mx player, it works fine. Can you please send me some steps? I greatly appreciate your help.  Thanks.

**Comment by islem19** [comment]
@ram2141 
you can change the line in MainFragment.java [reference here](https://github.com/islem19/TV-Live-Stream/blob/9f25d509c1924f8e809268f18f2e7b729ea0ba52/app/src/main/java/dz/islem/androidtvapp/fragment/MainFragment.java#L138) 
`bundle.putString("link","your_video_link");`
you can insert link directly here and it should work fine. i haven't implemented the part where it parses the json file, you can look that by yourself if you want to do it that way.

**Comment by ram2141** [comment]
Thank you @islem19  for your help. It worked.
