### ISSUE TITLE
Fetch json data on a remote server instead of local json

### ISSUE THREAD

**Issue by Mabudigital** [islem19/TV-Live-Stream#2]
I have my data JSON on a remote server. How can that data be fetched from a remote server instead of local data.json?

**Comment by islem19** [comment]
Check the [Remote Manager.java](https://github.com/islem19/TV-Live-Stream/blob/develop/app/src/main/java/dz/islem/androidtvapp/remote/RemoteManager.java) , the method below fetchData(),  retreive the data from the local resources RAW , you should override or modify the function to fetch the data from a remote service (check usage of retrofit lib) 
```
public void featchData(){
        Log.e("TAG", "featchData: " );
        String json = Utils.inputStreamToString(mContext.getResources().openRawResource(
                R.raw.data));
        LocalData dataRow = new Gson().fromJson(json, LocalData.class);
        mFragment.notifyOnTvDataAvailable(dataRow.getTv());
        mFragment.notifyOnRadioDataAvailable(dataRow.getRadio());
    }
`
